{{- if .Values.serviceMeshOperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.serviceMeshOperator.name "namespace" .Values.argocd.namespace "syncWave" "-1") }}
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/service-mesh-operator
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        subscription:
          source: {{ include "app-of-apps.operatorSource" . }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
