apiVersion: v2
name: service-mesh
description: A Helm chart for OpenShift Service Mesh 3.x
type: application
version: 0.1.0

dependencies:
  - name: service-mesh-operator
    version: 0.1.0
    repository: file://service-mesh-operator
