tenant:
  username: ""
  password: ""
  openshiftUser: ""
  namespacePrefix: "m3-"

sharedDatabase:
  namespace: shared-database-m3
  adminUser: dbadmin
  adminPassword: dbadmin123
  database: labdb

admin:
  namespace: admin-m3

s3:
  endpoint: ""
  accessKey: ""
  secretKey: ""
  invoiceUrl: "https://raw.githubusercontent.com/rh-app-connect-ai/lab-deploy-assets/main/invoices/invoice_61356291.pdf"
  invoiceFile: "invoice_61356291.pdf"
