namespace: openshift-operators

subscription:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace

argocd:
  syncwave:
    enabled: true
    subscription: "0"
