apiVersion: v1
kind: Secret
metadata:
  name: camel-credentials
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
type: Opaque
stringData:
  MATRIX_SYNAPSE_URL: "http://synapse.{{ .Values.matrix.namespace }}.svc:8008"
  ROCKETCHAT_URL: "http://rocketchat.{{ .Values.rocketchat.namespace }}.svc:3000"
