{{- $kuadrantNs := .Values.connectivityLink.kuadrantNamespace }}
{{- $username := .Values.tenant.username }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: m3-api-key-silver-{{ $username }}
  namespace: {{ $kuadrantNs }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: maasKey
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
  target:
    name: m3-api-key-silver-{{ $username }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          secret.kuadrant.io/upstream-token: "Bearer {{ "{{ .maasKey }}" }}"
          kuadrant.io/groups: silver
          secret.kuadrant.io/user-id: {{ $username | quote }}
        labels:
          authorino.kuadrant.io/managed-by: authorino
          app: my-llm-{{ $username }}
      data:
        _eso_managed: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: m3-api-key-gold-{{ $username }}
  namespace: {{ $kuadrantNs }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: maasKey
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
  target:
    name: m3-api-key-gold-{{ $username }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          secret.kuadrant.io/upstream-token: "Bearer {{ "{{ .maasKey }}" }}"
          kuadrant.io/groups: gold
          secret.kuadrant.io/user-id: {{ $username | quote }}
        labels:
          authorino.kuadrant.io/managed-by: authorino
          app: my-llm-{{ $username }}
      data:
        _eso_managed: "true"
