apiVersion: v1
kind: Secret
metadata:
  name: m3-api-key-silver-{{ .Values.tenant.username }}
  namespace: {{ .Values.connectivityLink.kuadrantNamespace }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
    authorino.kuadrant.io/managed-by: authorino
    app: my-llm-{{ .Values.tenant.username }}
  annotations:
    kuadrant.io/groups: silver
    secret.kuadrant.io/user-id: {{ .Values.tenant.username | quote }}
    secret.kuadrant.io/upstream-token: "Bearer {{ .Values.connectivityLink.maasKey }}"
stringData:
  api_key: {{ .Values.connectivityLink.silverApiKey | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: m3-api-key-gold-{{ .Values.tenant.username }}
  namespace: {{ .Values.connectivityLink.kuadrantNamespace }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
    authorino.kuadrant.io/managed-by: authorino
    app: my-llm-{{ .Values.tenant.username }}
  annotations:
    kuadrant.io/groups: gold
    secret.kuadrant.io/user-id: {{ .Values.tenant.username | quote }}
    secret.kuadrant.io/upstream-token: "Bearer {{ .Values.connectivityLink.maasKey }}"
stringData:
  api_key: {{ .Values.connectivityLink.goldApiKey | quote }}
type: Opaque
