apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-common-password
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: password
      remoteRef:
        key: secrets/common/password
        property: value
  target:
    name: vault-common-password
    creationPolicy: Owner
