apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
    {{- include "user-workload.labels" . | nindent 4 }}
  annotations:
    {{- include "user-workload.kafka-syncwave" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: {{ .Values.kafka.broker.replicas }}
  roles:
    - broker
  storage:
    type: ephemeral
