apiVersion: v1
kind: Secret
metadata:
  name: lab-credentials
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
type: Opaque
stringData:
  database.json: |
    {
      "username": "{{ .Values.tenant.username }}",
      "password": "{{ .Values.tenant.password }}",
      "host": "postgres.{{ .Values.sharedDatabase.namespace }}.svc.cluster.local",
      "port": "5432",
      "database": "{{ .Values.sharedDatabase.database }}",
      "schema": "{{ .Values.tenant.username }}"
    }
  openshift.json: |
    {
      "password": "{{ .Values.tenant.password }}"
    }
  s3.json: |
    {
      "accessKey": "{{ .Values.s3.accessKey }}",
      "secretKey": "{{ .Values.s3.secretKey }}",
      "endpoint": "{{ .Values.s3.endpoint }}",
      "bucket": "{{ .Values.tenant.username }}"
    }
