apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lab-credentials
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: password
      remoteRef:
        key: secrets/common/password
        property: value
    - secretKey: s3AccessKey
      remoteRef:
        key: secrets/s3/noobaa
        property: accessKey
    - secretKey: s3SecretKey
      remoteRef:
        key: secrets/s3/noobaa
        property: secretKey
    - secretKey: s3Endpoint
      remoteRef:
        key: secrets/s3/noobaa
        property: endpoint
  target:
    name: lab-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        database.json: |
          {
            "username": "{{ .Values.tenant.username }}",
            "password": "{{ "{{ .password }}" }}",
            "host": "postgres.{{ .Values.sharedDatabase.namespace }}.svc.cluster.local",
            "port": "5432",
            "database": "{{ .Values.sharedDatabase.database }}",
            "schema": "{{ .Values.tenant.username }}"
          }
        openshift.json: |
          {
            "password": "{{ "{{ .password }}" }}"
          }
        s3.json: |
          {
            "accessKey": "{{ "{{ .s3AccessKey }}" }}",
            "secretKey": "{{ "{{ .s3SecretKey }}" }}",
            "endpoint": "{{ "{{ .s3Endpoint }}" }}",
            "bucket": "{{ .Values.tenant.username }}"
          }
