apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "user-workload.namespace" . }}
  annotations:
    {{- include "user-workload.namespace-syncwave" . | nindent 4 }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
