apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
    {{- include "kafka-instance.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-instance.argocd-syncwave" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: {{ .Values.kafka.controller.replicas }}
  roles:
    - controller
  storage:
    type: ephemeral
