tenant:
  username: ""
  password: ""
  openshiftUser: ""
  namespacePrefix: ""

kafka:
  clusterName: my-cluster
  version: 4.1.0
  metadataVersion: 4.1-IV1
  broker:
    replicas: 1
  controller:
    replicas: 1
  config:
    offsetsTopicReplicationFactor: 1
    transactionStateLogReplicationFactor: 1
    transactionStateLogMinIsr: 1
    defaultReplicationFactor: 1
    minInsyncReplicas: 1

matrix:
  namespace: matrix-m3
  serverName: rhintegration.demo
  admin:
    username: admin
    password: admin

rocketchat:
  namespace: rocketchat-m3
  admin:
    username: rcadmin
    password: camel

helpdesk:
  namespace: helpdesk-m3
  admin:
    username: admin
    password: "Openshift1!"

sharedDatabase:
  namespace: shared-database-m3
  adminUser: dbadmin
  adminPassword: dbadmin123
  database: labdb

admin:
  namespace: admin-m3

s3:
  endpoint: ""
  accessKey: ""
  secretKey: ""
  invoiceUrl: "https://raw.githubusercontent.com/rh-app-connect-ai/lab-deploy-assets/main/invoices/invoice_61356291.pdf"
  invoiceFile: "invoice_61356291.pdf"

argocd:
  syncwave:
    enabled: true
    namespace: "-1"
    kafka: "0"
    matrix: "0"
    rocketchat: "0"
    helpdesk: "0"
