apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pv-claim
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "matrix.config-syncwave" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.synapse.storage.size }}
