gitops:
  repoURL: https://github.com/brunoNetId/test-gitops-m3.git
  targetRevision: main

argocd:
  namespace: openshift-gitops

cluster:
  subdomain: apps.cluster-szc5l.dyn.redhatworkshops.io

kafkaInstance:
  enabled: false
  name: kafka-instance
  namespace: test1-devspaces-module3

matrix:
  enabled: true
  name: matrix-m3
  namespace: matrix-m3

rocketchat:
  enabled: true
  name: rocketchat-m3
  namespace: rocketchat-m3

helpdesk:
  enabled: true
  name: helpdesk-m3
  namespace: helpdesk-m3

admin:
  enabled: true
  name: admin-m3
  namespace: admin-m3

sharedDatabase:
  enabled: true
  name: shared-database-m3
  namespace: shared-database-m3

camelFlows:
  enabled: true
  name: camel-flows-m3
  namespace: camel-flows-m3

filestash:
  enabled: true
  name: filestash-m3
  namespace: filestash-m3

connectivityLink:
  enabled: true
  name: connectivity-link-m3
  aiGateway:
    namespace: ai-gateway-m3
  llmApi:
    namespace: llm-api-m3
    host: maas-rhdp.apps.maas.redhatworkshops.io
