gitops:
  repoURL: https://github.com/brunoNetId/test-gitops-m3.git
  targetRevision: main

argocd:
  namespace: openshift-gitops

cluster:
  subdomain: apps.cluster-szc5l.dyn.redhatworkshops.io

kafkaInstance:
  enabled: true
  name: kafka-instance
  namespace: test1-devspaces-module3

matrix:
  enabled: true
  name: matrix-m3
  namespace: matrix-m3
